services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assettrack

    ports:
      - "5456:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d assettrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: unless-stopped

    command: >
      sh -c "
      sleep 10 &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

    ports:
      - "8000:8000"

    volumes:
      - ./app:/code/app
      - ./static:/code/static

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/assettrack
      SECRET_KEY: changethis_to_something_secure
      ALLOW_ORIGINS: '["*"]'

volumes:
  postgres_data:
