import { LoginAccess } from './LoginAccess';
import './landing.css';
import { ArrowUpRight, ArrowRight, Boxes, ScanLine, Headphones, Wrench, ShoppingCart, Columns3, Users, ShieldCheck, Smartphone, Radio, Check, ChevronDown } from 'lucide-react';

const modules = [
  { icon: Boxes, title: 'Cada ativo, uma história completa.', tag: '01 / PATRIMÔNIO', text: 'Do cadastro à baixa: E-Patrimônio, número de série, localização, responsável e histórico de movimentações.', items: ['Inventário com filtros', 'Etiquetas e leitura QR', 'Relatórios PDF e CSV'] },
  { icon: Headphones, title: 'Suporte que não perde o contexto.', tag: '02 / SERVICE DESK', text: 'Centralize chamados por categoria, setor e prioridade. Acompanhe responsáveis e interações com evidências em fotos.', items: ['Timeline de atendimento', 'Indicadores gerenciais', 'Alertas de emergência'] },
  { icon: Wrench, title: 'Manutenção com próximo passo.', tag: '03 / MANUTENÇÃO', text: 'Organize reparos e planos preventivos com periodicidade, checklists, ordens de serviço e registro de materiais.', items: ['Corretiva e preventiva', 'Evidências fotográficas', 'Histórico de execução'] },
  { icon: ShoppingCart, title: 'Da necessidade ao recebimento.', tag: '04 / COMPRAS', text: 'Conecte solicitações, aprovações, cotações e pedidos. O recebimento de equipamentos alimenta o inventário.', items: ['Centros de custo', 'Estoque e fornecedores', 'Contratos e garantias'] },
  { icon: Columns3, title: 'Projetos que saem do quadro.', tag: '05 / KANBAN', text: 'Distribua tarefas em colunas flexíveis, defina prazos e responsáveis e conecte os cards aos ativos e às compras.', items: ['Movimentação por arraste', 'Anexos e prioridades', 'Progresso do projeto'] },
  { icon: Users, title: 'Pessoas também fazem parte.', tag: '06 / RH', text: 'Organize termos de responsabilidade, calendário, status e comunicados. Gestores acompanham a equipe do seu setor.', items: ['Termos em PDF', 'Folgas, férias e banco de horas', 'Comunicação com gestor e RH'] },
];

export function LandingPage() {
  return <div className="public-landing">
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="nav"><a className="brand" href="#inicio" aria-label="AssetTrack TI, início"><Boxes size={29}/><span>assettrack<span className="brand-ti">TI</span></span></a><nav aria-label="Navegação principal"><a href="#plataforma">Plataforma</a><a href="#fluxo">Como funciona</a><a href="#mobilidade">Mobilidade</a></nav><LoginAccess /></header>
    <main id="conteudo">
      <section className="hero" id="inicio"><div className="hero-top"><span className="eyebrow"><span className="status-dot"/> GESTÃO DE TI, PONTA A PONTA</span><span className="hero-index">PATRIMÔNIO · PESSOAS · OPERAÇÃO</span></div>
        <div className="hero-grid"><div className="hero-copy"><h1>Sua TI conectada.<br/>Tudo sob <em>controle.</em></h1><p>Ativos, suporte e equipes no mesmo lugar. Transforme informações dispersas em uma operação organizada, do primeiro cadastro à próxima decisão.</p><a className="button lime" href="#plataforma">Conheça o AssetTrack <ArrowUpRight size={20}/></a><div className="hero-notes"><span><Check size={16}/> Rastreabilidade</span><span><Check size={16}/> Acesso por perfil</span><span><Check size={16}/> Web e Android</span></div></div><div className="hero-visual"><div className="visual-caption"><ScanLine size={22}/><span>IDENTIFIQUE. CONECTE. ACOMPANHE.</span></div><img className="hero-art" src="/assettrack-hero.png" alt="Ilustração de notebook, servidor, celular e etiquetas de patrimônio com leitura QR" width="1536" height="1024" fetchPriority="high"/><div className="asset-tag"><span className="tag-icon"><ShieldCheck size={23}/></span><div><strong>Histórico em cada movimento</strong><span>Do equipamento ao responsável</span></div><ArrowUpRight size={20}/></div></div></div>
        <div className="hero-bottom"><span>MENOS INFORMAÇÃO DISPERSA. MAIS VISIBILIDADE.</span><a href="#plataforma">Explore o que se conecta <ArrowRight size={17}/></a></div>
      </section>
      <section className="platform section" id="plataforma"><div className="section-heading"><div><span className="eyebrow">UMA PLATAFORMA. VÁRIAS CONEXÕES.</span><h2>A operação inteira.<br/><span>No mesmo fluxo.</span></h2></div><p>Os módulos acompanham o trabalho real da sua equipe — e mantêm o contexto entre uma etapa e outra.</p></div><div className="module-grid">{modules.map(({icon:Icon,title,tag,text,items})=><article className="module" key={tag}><div className="module-top"><Icon size={27} strokeWidth={1.5}/><span>{tag}</span></div><h3>{title}</h3><p>{text}</p><ul>{items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul></article>)}</div></section>
      <section className="flow section" id="fluxo"><div className="section-heading"><div><span className="eyebrow">DO PEDIDO AO HISTÓRICO</span><h2>Cada etapa deixa<br/>um caminho claro.</h2></div><p>Um equipamento não é só um item na lista. Ele conecta uma compra, uma pessoa e toda uma rotina de cuidado.</p></div><ol className="steps">{[['Solicite e aprove','Registre a necessidade, compare cotações e acompanhe o pedido de compra.'],['Receba e identifique','Integre o recebimento ao inventário e identifique o ativo pelo E-Patrimônio.'],['Entregue e registre','Vincule o responsável, valide a entrega por QR e acompanhe o termo de responsabilidade.'],['Cuide e acompanhe','Conecte chamados, manutenções e movimentações ao histórico do equipamento.']].map(([title,text],i)=><li key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
      <section className="mobile section" id="mobilidade"><div className="mobile-symbol"><Smartphone size={70} strokeWidth={1}/><ScanLine size={40} strokeWidth={1.3}/><span>DA MESA AO INVENTÁRIO</span></div><div><span className="eyebrow">A OPERAÇÃO VAI COM VOCÊ</span><h2>Menos distância<br/>entre ver e agir.</h2><p>Acesse pelo navegador ou pelo aplicativo Android. Leia etiquetas QR, consulte equipamentos e acompanhe as demandas onde o trabalho acontece.</p><div className="mobile-details"><span><ScanLine/> Leitura QR de ativos</span><span><Smartphone/> Web, PWA e Android</span></div><p className="small-note">O APK é disponibilizado pelo portal da sua organização. O acesso depende do endereço e das permissões configurados pela equipe responsável.</p></div></section>
      <section className="operations section"><div className="section-heading"><div><span className="eyebrow">VISIBILIDADE COM RESPONSABILIDADE</span><h2>A informação certa.<br/>Para quem precisa.</h2></div></div><div className="operations-grid"><article><ShieldCheck/><h3>Acesso por perfil</h3><p>Permissões por função e módulos configuráveis. No RH, gestores acompanham a equipe atribuída ao seu setor.</p></article><article><Radio/><h3>Operação à vista</h3><p>Dashboard, alertas emergenciais e sala de monitoramento para acompanhar filas, prioridades e responsáveis.</p></article><article><Boxes/><h3>Contexto para decidir</h3><p>Relatórios, exportações e histórico ajudam a conferir o inventário e acompanhar a evolução da operação.</p></article></div></section>
      <section className="faq section"><div><span className="eyebrow">BOM SABER</span><h2>Conecte os pontos.</h2></div><div className="faq-items">{[['Para quais equipes o AssetTrack TI foi pensado?','Para gestores de TI e infraestrutura, técnicos, compradores, RH e colaboradores. Cada perfil acessa os recursos correspondentes às suas permissões.'],['Preciso instalar um aplicativo?','A plataforma pode ser acessada pelo navegador. Também há suporte a PWA e aplicativo Android, disponibilizado no portal da organização.'],['O que pode ser rastreado no inventário?','O cadastro reúne identificação por E-Patrimônio, número de série, categoria, localização, responsável e histórico de movimentações. Filtros e exportações apoiam a conferência.'],['Esta página dá acesso aos dados da organização?','Esta é a apresentação pública do AssetTrack TI. Os dados operacionais ficam na aplicação da organização, com autenticação e controle de acesso. Para entrar, utilize o endereço informado pela sua equipe de TI.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={20}/></summary><p>{a}</p></details>)}</div></section>
      <section className="closing"><span className="eyebrow">ASSETTRACK TI</span><h2>Mais conexão.<br/><em>Mais controle.</em></h2><a className="button dark-button" href="#plataforma">Explore as funcionalidades <ArrowUpRight size={20}/></a><p>Do patrimônio às pessoas. Uma operação que faz sentido.</p></section>
    </main><footer><a className="brand" href="#inicio"><Boxes size={27}/><span>assettrack<span className="brand-ti">TI</span></span></a><p>Gestão de ativos e operações de TI.</p><a href="#inicio">Voltar ao topo ↑</a></footer>
  </div>;
}
